[versions]
minSdk = "28"
targetSdk = "35"
compileSdk = "35"
mapSdk = "3.23.1"

agp = "8.8.2"
kotlin = "2.1.10"
ksp = "2.1.10-1.0.31"
hilt = "2.55"
room = "2.7.2"
material = "1.12.0"
android-tools = "31.11.1"
androidx-activity = "1.10.1"
coil = "2.7.0"
accompanist = "0.36.0"
retrofit = "3.0.0"
firebase-crashlytics = "3.0.3"
secrets-gradle-plugin = "2.0.1"
firebaseCrashlyticsGradle = "3.0.6"
playServicesWearable = "19.0.0"
composeMaterial = "1.2.1"
composeFoundation = "1.2.1"
wearToolingPreview = "1.0.0"
tiles = "1.4.0"
tilesMaterial = "1.4.0"
tilesTooling = "1.4.0"
tilesToolingPreview = "1.4.0"
horologistComposeTools = "0.6.17"
horologistTiles = "0.6.17"
watchfaceComplicationsDataSourceKtx = "1.2.1"
protolayout = "1.2.0"
media3 = "1.7.1"
threetenapb = "1.3.0"
glide = "4.16.0"
glide-transformation = "4.3.0"
hazeVerion = "1.3.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-test = { id = "com.android.test", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.0.0" }
android-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-services = { id = "com.google.gms.google-services", version = "4.4.2" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics" }
secrets-gradle-plugin = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secrets-gradle-plugin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version = "2.2.0" }

# Custom Convention Plugin
codehong-android-application = { id = "codehong.android.application", version = "unspecified" }
codehong-android-application-compose = { id = "codehong.android.application.compose", version = "unspecified" }
codehong-android-library = { id = "codehong.android.library", version = "unspecified" }
codehong-android-library-compose = { id = "codehong.android.library.compose", version = "unspecified" }
codehong-android-library-publishing = { id = "codehong.library.publishing", version = "unspecified" }
codehong-android-library-bom-publishing = { id = "codehong.library.bom.publishing", version = "unspecified" }
codehong-android-build-type = { id = "codehong.android.build-type", version = "unspecified" }
codehong-android-flavor = { id = "codehong.android.flavor", version = "unspecified" }
codehong-android-firebase = { id = "codehong.android.firebase", version = "unspecified" }
codehong-android-hilt = { id = "codehong.android.hilt", version = "unspecified" }
codehong-android-room = { id = "codehong.android.room", version = "unspecified" }
codehong-android-network = { id = "codehong.android.network", version = "unspecified" }

[libraries]
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
compose-gradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "android-tools" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
room-gradlePlugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "room" }
firebase-crashlytics-gradlePlugin = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version.ref = "firebase-crashlytics" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.16.0" }
junit = { group = "junit", name = "junit", version = "4.13.2" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version = "1.2.1" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version = "3.6.1" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version = "2.9.2" }

androidx-multidex = { group = "androidx.multidex", name = "multidex", version = "2.0.0" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "androidx-activity" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidx-activity" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment", version = "1.5.2" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.7.1" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.2.1" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version = "1.4.0" }
androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version = "1.1.0" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version = "1.0.1" }

# compose
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version = "1.10.1" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version = "2025.06.01" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version = "1.4.0-alpha17" }
androidx-compose-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core" }
androidx-compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
androidx-compose-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version = "2.6.1" }
androidx-compose-foundation-layout-android = { group = "androidx.compose.foundation", name = "foundation-layout-android", version = "1.6.8" }
androidx-compose-material3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive" }
composables-core = { group = "com.composables", name = "core", version = "1.31.1" } # 1.32.0 버전부터는 kotlin 2.1.21, compose 1.8.1 이상 필요
sh-calvin-reorderable = { group = "sh.calvin.reorderable", name = "reorderable", version = "3.0.0" }
androidx-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }


google-android-gms-location = { group = "com.google.android.gms", name = "play-services-location", version = "21.3.0" }
google-android-gms-map = { group = "com.google.android.gms", name = "play-services-maps", version = "19.2.0" }

google-accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }
google-accompanist-flowlayout = { group = "com.google.accompanist", name = "accompanist-flowlayout", version.ref = "accompanist" }
google-accompanist-pager = { group = "com.google.accompanist", name = "accompanist-pager", version.ref = "accompanist" }
google-accompanist-pager-indicators = { group = "com.google.accompanist", name = "accompanist-pager-indicators", version.ref = "accompanist" }

# https://developer.android.com/jetpack/androidx/releases/room?hl=ko
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" } # androidTestImplementation

# retrofit
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
retrofit-converter-scalars = { group = "com.squareup.retrofit2", name = "converter-scalars", version.ref = "retrofit" }
retrofit-converter-simplexml = { group = "com.squareup.retrofit2", name = "converter-simplexml", version.ref = "retrofit" }
retrofit-converter-kotlinx-serialization = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref = "retrofit" }

# https://github.com/google/gson/blob/main/CHANGELOG.md
gson = { group = "com.google.code.gson", name = "gson", version = "2.13.1" }

# okhttp
okhttp-bom = { group = "com.squareup.okhttp3", name = "okhttp-bom", version = "4.12.0" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor" }
okhttp-urlconnection = { group = "com.squareup.okhttp3", name = "okhttp-urlconnection" }

# hilt
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version = "1.1.0" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" } # androidTestImplementation

# https://coil-kt.github.io/coil/changelog/
coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-svg = { group = "io.coil-kt", name = "coil-svg", version.ref = "coil" }
coil-gif = { group = "io.coil-kt", name = "coil-gif", version.ref = "coil" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

# glide
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
#glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide" }
glide-transformation = { group = "jp.wasabeef", name = "glide-transformations", version.ref = "glide-transformation" }
glide-ksp = { group = "com.github.bumptech.glide", name = "ksp", version.ref = "glide" }

material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# debug
timber = { group = "com.jakewharton.timber", name = "timber", version = "5.0.1" }

# https://firebase.google.com/support/release-notes/android
firebase-bom = "com.google.firebase:firebase-bom:33.14.0"
firebase-config = { group = "com.google.firebase", name = "firebase-config" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
play-services-wearable = { group = "com.google.android.gms", name = "play-services-wearable", version.ref = "playServicesWearable" }

horologist-compose-tools = { group = "com.google.android.horologist", name = "horologist-compose-tools", version.ref = "horologistComposeTools" }
horologist-tiles = { group = "com.google.android.horologist", name = "horologist-tiles", version.ref = "horologistTiles" }
androidx-watchface-complications-data-source-ktx = { group = "androidx.wear.watchface", name = "watchface-complications-data-source-ktx", version.ref = "watchfaceComplicationsDataSourceKtx" }

# lottie
# https://github.com/airbnb/lottie-android/blob/master/CHANGELOG.md
lottie = { group = "com.airbnb.android", name = "lottie", version = "6.6.6" }
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version = "6.6.6" }

# exoplayer
androidx-media = { group = "androidx.media", name = "media", version = "1.5.0" }
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3" }
androidx-media3-exoplayer-hls = { group = "androidx.media3", name = "media3-exoplayer-hls", version.ref = "media3" }
androidx-media3-common-ktx = { group = "androidx.media3", name = "media3-common-ktx", version.ref = "media3" }
androidx-media3-datasource = { group = "androidx.media3", name = "media3-datasource", version.ref = "media3" }

# naver map
naver-map-sdk = { module = "com.naver.maps:map-sdk", version.ref = "mapSdk" }
naver-map-compose = { group = "io.github.fornewid", name = "naver-map-compose", version = "1.9.0" }
naver-map-location = { group = "io.github.fornewid", name = "naver-map-location", version = "21.0.2" }

# etc
threetenapb = { group = "com.jakewharton.threetenabp", name = "threetenabp", version.ref = "threetenapb" }
haze = { group = "dev.chrisbanes.haze", name = "haze", version.ref = "hazeVerion" }

# palette
androidx-palette = { group = "androidx.palette", name = "palette-ktx", version = "1.0.0" }

kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version = "1.9.0" }

[bundles]
#retrofit = ["retrofit", "retrofit-gson", "retrofit-scalars", "retrofit-simplexml", "retrofit-converter-kotlinx-serialization"]
coil = ["coil", "coil-svg", "coil-gif", "coil-compose"]
glide = ["glide", "glide-transformation", "glide-ksp"]